### ISSUE TITLE
Debugger entered--Lisp error: (void-variable apheleia-formatters)

### ISSUE THREAD

**Issue by avatar-lavventura** [raxod502/apheleia#75]
When I add following lines into my init.el file:

```
(setf (alist-get 'isort apheleia-formatters)
      '("isort" "--stdout" "-"))
(setf (alist-get 'python-mode apheleia-mode-alist)
      '(isort black))
```

------------------

I am getting following error:

```
Debugger entered--Lisp error: (void-variable apheleia-formatters)
  (assq 'isort apheleia-formatters)
  (if (and nil (not (eq nil 'eq))) (assoc 'isort apheleia-formatters nil) (assq 'isort apheleia-formatters))
  (let* ((p (if (and nil (not (eq nil 'eq))) (assoc 'isort apheleia-formatters nil) (assq 'isort apheleia-formatters)))) (progn
(if p (setcdr p '("isort" "--stdout" "-")) (setq apheleia-formatters (cons (setq p (cons 'isort '...)) apheleia-formatters)))
'("isort" "--stdout" "-")))
  load-with-code-conversion("/home/alper/.emacs" "/home/alper/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x10f36531c68d12d2>) #f(compiled-function () #<bytecode
-0x1f3c686ddc0ca9b5>) t)
  command-line()
  normal-top-level()
```

How can I prevent this error?

**Comment by mohkale** [comment]
You have to modify the variable after apheleia has been loaded.

```lisp
(with-eval-after-load 'apheleia
(setf (alist-get 'isort apheleia-formatters)
      '("isort" "--stdout" "-"))
(setf (alist-get 'python-mode apheleia-mode-alist)
      '(isort black))
  )
```

**Comment by avatar-lavventura** [comment]
@mohkale Thanks. I have `isort` installed but I am getting following message now:

```
$ isort --stdout -

Traceback (most recent call last):
  File "/home/alper/venv/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/alper/venv/lib/python3.8/site-packages/isort/main.py", line 343, in main
    SortImports(file_=file_, write_to_stdout=True, **arguments)
TypeError: type object got multiple values for keyword argument 'write_to_stdout'

Command failed with exit code 1.
```

**Comment by mohkale** [comment]
@avatar-lavventura 

I got this error a while back as well. I can't remember what I did to fix it, but try upgrading your isort version.

**Comment by avatar-lavventura** [comment]
@mohkale Upgrade solves it :-)

**Comment by raxod502** [comment]
Nice, thanks all!
